# Generated by Django 4.2.13 on 2024-06-06 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OctaveAssignment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OctaveBattery',
        ),
    ]
