# Generated by Django 4.2.13 on 2024-06-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OctaveAssignment', '0002_delete_octavebattery'),
    ]

    operations = [
        migrations.CreateModel(
            name='OctaveBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('maximum_power', models.IntegerField()),
                ('state_of_charge', models.FloatField()),
                ('cycles', models.FloatField()),
            ],
        ),
    ]
