# Generated by Django 4.2.13 on 2024-06-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OctaveAssignment", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="octavebattery",
            name="cycles",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="octavebattery",
            name="state_of_charge",
            field=models.FloatField(default=0.5),
        ),
    ]
