# Generated by Django 4.2.13 on 2024-06-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OctaveAssignment", "0004_alter_octavebattery_cycles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="octavebattery",
            name="charging",
            field=models.BooleanField(default=False),
        ),
    ]
